### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by andlo** [microsoft/ptvsd#1682]
## Environment data

- PTVSD version: 4.3.0
- OS and version: Raspbian Strech (Debian 9.8)
- Python version (& distribution if applicable, e.g. Anaconda): 3.5.3
- Using VS Code or Visual Studio: VS Code (THEIA IDE) 

## Actual behavior
In a module I add 
```
import ptvsd
ptvsd.enable_attach()
```
but when loading the module I get `ValueError: signal only works in main thread`

Full traceback when loading module:
```
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 131, in load_skill
    imp.PY_SOURCE))
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/mycroft/skills/count-skill/__init__.py", line 22, in <module>
    ptvsd.enable_attach()
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/_remote.py", line 64, in enable_attach
    **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/pydevd_hooks.py", line 128, in install
    daemon = Daemon(**kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/daemon.py", line 503, in __init__
    super(Daemon, self).__init__(wait_for_user, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/daemon.py", line 100, in __init__
    self._install_exit_handlers()
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/daemon.py", line 425, in _install_exit_handlers
    self._exithandlers.install()
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/exit_handlers.py", line 62, in install
    self._install_signal_handler()
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/ptvsd/exit_handlers.py", line 103, in _install_signal_handler
    orig[sig] = signal.signal(sig, self._signal_handler)
  File "/usr/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

## Expected  behavior
I would expect that a debug server were started so I could attach to that

**Comment by int19h** [comment]
@karthiknadig I think that we might have already fixed this in the refactor branch, actually, since daemon is gone there.

**Comment by andlo** [comment]
> @karthiknadig I think that we might have already fixed this in the refactor branch, actually, since daemon is gone there.

I did try the dbg_adapter_refactor but it fails during install

```
pi@mycroft:~/work/ptvsd $ git checkout dbg_adapter_refactor
Already on 'dbg_adapter_refactor'
Your branch is up-to-date with 'origin/dbg_adapter_refactor'.
pi@mycroft:~/work/ptvsd $ pip install ./
Processing /home/pi/work/ptvsd
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6vdnzqjj/setup.py", line 31, in <module>
        import ptvsd
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/__init__.py", line 40, in <module>
        from ptvsd.server.attach import (
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/server/__init__.py", line 9, in <module>
        import ptvsd._vendored.force_pydevd # noqa
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/_vendored/force_pydevd.py", line 43, in <module>
        'pydevd',
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/_vendored/__init__.py", line 129, in preimport
        import_module(name)
      File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/_vendored/pydevd/pydevd.py", line 30, in <module>
        from _pydevd_bundle.pydevd_additional_thread_info import set_additional_thread_info
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info.py", line 17, in <module>
        from _pydevd_bundle.pydevd_cython_wrapper import PyDBAdditionalThreadInfo, set_additional_thread_info, _set_additional_thread_info_lock
      File "/tmp/pip-req-build-6vdnzqjj/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_cython_wrapper.py", line 42, in <module>
        set_additional_thread_info = mod.set_additional_thread_info
    AttributeError: module '_pydevd_bundle.pydevd_cython' has no attribute 'set_additional_thread_info'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-6vdnzqjj/
```

**Comment by int19h** [comment]
This might be another manifestation of #1677, since that is a native (Cython) module that it can't find the member in, judging by that call stack.

(@fabioz, possibly another place where we need to gracefully handle non-Intel arch, and fall back to pure Python code?)

@andlo, can you please try this to help diagnose it?
```sh
cd ~/work/ptvsd/src/ptvsd/_vendored
python -c "import _pydevd_bundle.pydevd_cython as m; print(m.__file__)"
```

Then try setting `PYDEVD_USE_CYTHON=NO` in environment, and see if that helps.

Side note: you don't need to pip install ptvsd as a package to run it - `python ~/work/ptvsd` will also work.

**Comment by fabioz** [comment]
This particular error is because the branch is not updated with the master
(when we merge the master into the reactor branch this should be fixed...
this happened because the compiled extension is not up to date in the
refactor branch)... setting to not use the compiled extension should be a
reasonable workaround for now.

**Comment by andlo** [comment]
> Then try setting PYDEVD_USE_CYTHON=NO in environment, and see if that helps.
It helped and I got it working. But then ran into other issues.
When the mainthread module is reloading and then the old threds (prosesses) arent stoped or killed leaving me with more and more prosesses and stil unavable to atatch to the debugger :( 

In my setup the right way is to attatch to a pid I think. But try more, but I am not that good at this stuff but am learning every day :)

**Comment by andaag** [comment]
Eny eta on getting this on master? I'm hitting this in the linked issue.

**Comment by int19h** [comment]
It's already in master, and in ptvsd 5.0.0 pre-releases. You should be able to just do `pip install --pre` to get it for testing.

**Comment by jflam** [comment]
I'm still seeing this issue repro using:

- Python 3.7.7 on
- Windows Insider build 20262
- Ubuntu 18.04 LTS
- current streamlit bits on PyPI (0.71.0)
- current ptvsd bits on PyPI (4.3.2)
- release VS Code (1.51.1)
- release python extension (2020.11.371526539) <= lol the release version # 

Would love to be able to debug streamlit on WSL2 using our tools :) 

![image](https://user-images.githubusercontent.com/8877/100052422-c798e400-2dd2-11eb-9019-21731bb432c2.png)

**Comment by fabioz** [comment]
@jflam `ptvsd` is no longer supported (see: https://github.com/microsoft/ptvsd/blob/master/README.md for details).
